package com.liudehuang.boot.security.jwttoken.mapper;

import com.liudehuang.boot.security.jwttoken.model.domain.BaseUserRole;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface BaseUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user_role
     *
     * @mbggenerated
     */
    int insert(BaseUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user_role
     *
     * @mbggenerated
     */
    int insertSelective(BaseUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user_role
     *
     * @mbggenerated
     */
    BaseUserRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseUserRole record);
}