package com.liudehuang.boot.security.jwttoken.mapper;

import com.liudehuang.boot.security.jwttoken.model.domain.BaseMenu;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface BaseMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbggenerated
     */
    int insert(BaseMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbggenerated
     */
    int insertSelective(BaseMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbggenerated
     */
    BaseMenu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseMenu record);
}