server:
  port: 8095
spring:
  application:
    name: sentinel-feign-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719
      filter:
        enabled: false
      pathvariable:
        skip:
          list: orderId
feign:
  sentinel:
    enabled: true
