package com.liudehuang.boot.druid.entity;

import java.util.Date;

public class KanjiaOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kanjia_order.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kanjia_order.merchant_id
     *
     * @mbggenerated
     */
    private Long merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kanjia_order.activity_id
     *
     * @mbggenerated
     */
    private Long activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kanjia_order.activity_name
     *
     * @mbggenerated
     */
    private String activityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kanjia_order.kanjia_no
     *
     * @mbggenerated
     */
    private String kanjiaNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kanjia_order.order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kanjia_order.item_no
     *
     * @mbggenerated
     */
    private String itemNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kanjia_order.item_name
     *
     * @mbggenerated
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kanjia_order.origin_price
     *
     * @mbggenerated
     */
    private Integer originPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kanjia_order.deal_price
     *
     * @mbggenerated
     */
    private Integer dealPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kanjia_order.expire_date
     *
     * @mbggenerated
     */
    private Date expireDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kanjia_order.success_time
     *
     * @mbggenerated
     */
    private Date successTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kanjia_order.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kanjia_order.card_id
     *
     * @mbggenerated
     */
    private String cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kanjia_order.open_id
     *
     * @mbggenerated
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kanjia_order.wx_name
     *
     * @mbggenerated
     */
    private String wxName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kanjia_order.wx_img
     *
     * @mbggenerated
     */
    private String wxImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kanjia_order.created_by
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kanjia_order.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kanjia_order.updated_by
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kanjia_order.updated_time
     *
     * @mbggenerated
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kanjia_order.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kanjia_order.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kanjia_order.id
     *
     * @return the value of kanjia_order.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kanjia_order.id
     *
     * @param id the value for kanjia_order.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kanjia_order.merchant_id
     *
     * @return the value of kanjia_order.merchant_id
     *
     * @mbggenerated
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kanjia_order.merchant_id
     *
     * @param merchantId the value for kanjia_order.merchant_id
     *
     * @mbggenerated
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kanjia_order.activity_id
     *
     * @return the value of kanjia_order.activity_id
     *
     * @mbggenerated
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kanjia_order.activity_id
     *
     * @param activityId the value for kanjia_order.activity_id
     *
     * @mbggenerated
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kanjia_order.activity_name
     *
     * @return the value of kanjia_order.activity_name
     *
     * @mbggenerated
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kanjia_order.activity_name
     *
     * @param activityName the value for kanjia_order.activity_name
     *
     * @mbggenerated
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kanjia_order.kanjia_no
     *
     * @return the value of kanjia_order.kanjia_no
     *
     * @mbggenerated
     */
    public String getKanjiaNo() {
        return kanjiaNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kanjia_order.kanjia_no
     *
     * @param kanjiaNo the value for kanjia_order.kanjia_no
     *
     * @mbggenerated
     */
    public void setKanjiaNo(String kanjiaNo) {
        this.kanjiaNo = kanjiaNo == null ? null : kanjiaNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kanjia_order.order_no
     *
     * @return the value of kanjia_order.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kanjia_order.order_no
     *
     * @param orderNo the value for kanjia_order.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kanjia_order.item_no
     *
     * @return the value of kanjia_order.item_no
     *
     * @mbggenerated
     */
    public String getItemNo() {
        return itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kanjia_order.item_no
     *
     * @param itemNo the value for kanjia_order.item_no
     *
     * @mbggenerated
     */
    public void setItemNo(String itemNo) {
        this.itemNo = itemNo == null ? null : itemNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kanjia_order.item_name
     *
     * @return the value of kanjia_order.item_name
     *
     * @mbggenerated
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kanjia_order.item_name
     *
     * @param itemName the value for kanjia_order.item_name
     *
     * @mbggenerated
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kanjia_order.origin_price
     *
     * @return the value of kanjia_order.origin_price
     *
     * @mbggenerated
     */
    public Integer getOriginPrice() {
        return originPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kanjia_order.origin_price
     *
     * @param originPrice the value for kanjia_order.origin_price
     *
     * @mbggenerated
     */
    public void setOriginPrice(Integer originPrice) {
        this.originPrice = originPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kanjia_order.deal_price
     *
     * @return the value of kanjia_order.deal_price
     *
     * @mbggenerated
     */
    public Integer getDealPrice() {
        return dealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kanjia_order.deal_price
     *
     * @param dealPrice the value for kanjia_order.deal_price
     *
     * @mbggenerated
     */
    public void setDealPrice(Integer dealPrice) {
        this.dealPrice = dealPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kanjia_order.expire_date
     *
     * @return the value of kanjia_order.expire_date
     *
     * @mbggenerated
     */
    public Date getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kanjia_order.expire_date
     *
     * @param expireDate the value for kanjia_order.expire_date
     *
     * @mbggenerated
     */
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kanjia_order.success_time
     *
     * @return the value of kanjia_order.success_time
     *
     * @mbggenerated
     */
    public Date getSuccessTime() {
        return successTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kanjia_order.success_time
     *
     * @param successTime the value for kanjia_order.success_time
     *
     * @mbggenerated
     */
    public void setSuccessTime(Date successTime) {
        this.successTime = successTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kanjia_order.status
     *
     * @return the value of kanjia_order.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kanjia_order.status
     *
     * @param status the value for kanjia_order.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kanjia_order.card_id
     *
     * @return the value of kanjia_order.card_id
     *
     * @mbggenerated
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kanjia_order.card_id
     *
     * @param cardId the value for kanjia_order.card_id
     *
     * @mbggenerated
     */
    public void setCardId(String cardId) {
        this.cardId = cardId == null ? null : cardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kanjia_order.open_id
     *
     * @return the value of kanjia_order.open_id
     *
     * @mbggenerated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kanjia_order.open_id
     *
     * @param openId the value for kanjia_order.open_id
     *
     * @mbggenerated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kanjia_order.wx_name
     *
     * @return the value of kanjia_order.wx_name
     *
     * @mbggenerated
     */
    public String getWxName() {
        return wxName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kanjia_order.wx_name
     *
     * @param wxName the value for kanjia_order.wx_name
     *
     * @mbggenerated
     */
    public void setWxName(String wxName) {
        this.wxName = wxName == null ? null : wxName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kanjia_order.wx_img
     *
     * @return the value of kanjia_order.wx_img
     *
     * @mbggenerated
     */
    public String getWxImg() {
        return wxImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kanjia_order.wx_img
     *
     * @param wxImg the value for kanjia_order.wx_img
     *
     * @mbggenerated
     */
    public void setWxImg(String wxImg) {
        this.wxImg = wxImg == null ? null : wxImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kanjia_order.created_by
     *
     * @return the value of kanjia_order.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kanjia_order.created_by
     *
     * @param createdBy the value for kanjia_order.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kanjia_order.created_time
     *
     * @return the value of kanjia_order.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kanjia_order.created_time
     *
     * @param createdTime the value for kanjia_order.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kanjia_order.updated_by
     *
     * @return the value of kanjia_order.updated_by
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kanjia_order.updated_by
     *
     * @param updatedBy the value for kanjia_order.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kanjia_order.updated_time
     *
     * @return the value of kanjia_order.updated_time
     *
     * @mbggenerated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kanjia_order.updated_time
     *
     * @param updatedTime the value for kanjia_order.updated_time
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kanjia_order.remark
     *
     * @return the value of kanjia_order.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kanjia_order.remark
     *
     * @param remark the value for kanjia_order.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kanjia_order.deleted
     *
     * @return the value of kanjia_order.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kanjia_order.deleted
     *
     * @param deleted the value for kanjia_order.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}