package com.liudehuang.boot.druid.entity;

import java.util.Date;

public class MeetGift {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_gift.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_gift.activity_id
     *
     * @mbggenerated
     */
    private Long activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_gift.merchant_id
     *
     * @mbggenerated
     */
    private Long merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_gift.rank_id
     *
     * @mbggenerated
     */
    private Long rankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_gift.gift_id
     *
     * @mbggenerated
     */
    private Long giftId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_gift.gift_code
     *
     * @mbggenerated
     */
    private String giftCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_gift.gift_type
     *
     * @mbggenerated
     */
    private Integer giftType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_gift.gift_name
     *
     * @mbggenerated
     */
    private String giftName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_gift.gift_value
     *
     * @mbggenerated
     */
    private Integer giftValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_gift.gift_stock
     *
     * @mbggenerated
     */
    private Integer giftStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_gift.gift_surplus_stock
     *
     * @mbggenerated
     */
    private Integer giftSurplusStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_gift.give_quantity
     *
     * @mbggenerated
     */
    private Integer giveQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_gift.preferential
     *
     * @mbggenerated
     */
    private Integer preferential;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_gift.show_order
     *
     * @mbggenerated
     */
    private Integer showOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_gift.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_gift.created_by
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_gift.updated_time
     *
     * @mbggenerated
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_gift.updated_by
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_gift.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_gift.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_gift.id
     *
     * @return the value of meet_gift.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_gift.id
     *
     * @param id the value for meet_gift.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_gift.activity_id
     *
     * @return the value of meet_gift.activity_id
     *
     * @mbggenerated
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_gift.activity_id
     *
     * @param activityId the value for meet_gift.activity_id
     *
     * @mbggenerated
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_gift.merchant_id
     *
     * @return the value of meet_gift.merchant_id
     *
     * @mbggenerated
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_gift.merchant_id
     *
     * @param merchantId the value for meet_gift.merchant_id
     *
     * @mbggenerated
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_gift.rank_id
     *
     * @return the value of meet_gift.rank_id
     *
     * @mbggenerated
     */
    public Long getRankId() {
        return rankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_gift.rank_id
     *
     * @param rankId the value for meet_gift.rank_id
     *
     * @mbggenerated
     */
    public void setRankId(Long rankId) {
        this.rankId = rankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_gift.gift_id
     *
     * @return the value of meet_gift.gift_id
     *
     * @mbggenerated
     */
    public Long getGiftId() {
        return giftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_gift.gift_id
     *
     * @param giftId the value for meet_gift.gift_id
     *
     * @mbggenerated
     */
    public void setGiftId(Long giftId) {
        this.giftId = giftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_gift.gift_code
     *
     * @return the value of meet_gift.gift_code
     *
     * @mbggenerated
     */
    public String getGiftCode() {
        return giftCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_gift.gift_code
     *
     * @param giftCode the value for meet_gift.gift_code
     *
     * @mbggenerated
     */
    public void setGiftCode(String giftCode) {
        this.giftCode = giftCode == null ? null : giftCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_gift.gift_type
     *
     * @return the value of meet_gift.gift_type
     *
     * @mbggenerated
     */
    public Integer getGiftType() {
        return giftType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_gift.gift_type
     *
     * @param giftType the value for meet_gift.gift_type
     *
     * @mbggenerated
     */
    public void setGiftType(Integer giftType) {
        this.giftType = giftType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_gift.gift_name
     *
     * @return the value of meet_gift.gift_name
     *
     * @mbggenerated
     */
    public String getGiftName() {
        return giftName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_gift.gift_name
     *
     * @param giftName the value for meet_gift.gift_name
     *
     * @mbggenerated
     */
    public void setGiftName(String giftName) {
        this.giftName = giftName == null ? null : giftName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_gift.gift_value
     *
     * @return the value of meet_gift.gift_value
     *
     * @mbggenerated
     */
    public Integer getGiftValue() {
        return giftValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_gift.gift_value
     *
     * @param giftValue the value for meet_gift.gift_value
     *
     * @mbggenerated
     */
    public void setGiftValue(Integer giftValue) {
        this.giftValue = giftValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_gift.gift_stock
     *
     * @return the value of meet_gift.gift_stock
     *
     * @mbggenerated
     */
    public Integer getGiftStock() {
        return giftStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_gift.gift_stock
     *
     * @param giftStock the value for meet_gift.gift_stock
     *
     * @mbggenerated
     */
    public void setGiftStock(Integer giftStock) {
        this.giftStock = giftStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_gift.gift_surplus_stock
     *
     * @return the value of meet_gift.gift_surplus_stock
     *
     * @mbggenerated
     */
    public Integer getGiftSurplusStock() {
        return giftSurplusStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_gift.gift_surplus_stock
     *
     * @param giftSurplusStock the value for meet_gift.gift_surplus_stock
     *
     * @mbggenerated
     */
    public void setGiftSurplusStock(Integer giftSurplusStock) {
        this.giftSurplusStock = giftSurplusStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_gift.give_quantity
     *
     * @return the value of meet_gift.give_quantity
     *
     * @mbggenerated
     */
    public Integer getGiveQuantity() {
        return giveQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_gift.give_quantity
     *
     * @param giveQuantity the value for meet_gift.give_quantity
     *
     * @mbggenerated
     */
    public void setGiveQuantity(Integer giveQuantity) {
        this.giveQuantity = giveQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_gift.preferential
     *
     * @return the value of meet_gift.preferential
     *
     * @mbggenerated
     */
    public Integer getPreferential() {
        return preferential;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_gift.preferential
     *
     * @param preferential the value for meet_gift.preferential
     *
     * @mbggenerated
     */
    public void setPreferential(Integer preferential) {
        this.preferential = preferential;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_gift.show_order
     *
     * @return the value of meet_gift.show_order
     *
     * @mbggenerated
     */
    public Integer getShowOrder() {
        return showOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_gift.show_order
     *
     * @param showOrder the value for meet_gift.show_order
     *
     * @mbggenerated
     */
    public void setShowOrder(Integer showOrder) {
        this.showOrder = showOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_gift.created_time
     *
     * @return the value of meet_gift.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_gift.created_time
     *
     * @param createdTime the value for meet_gift.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_gift.created_by
     *
     * @return the value of meet_gift.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_gift.created_by
     *
     * @param createdBy the value for meet_gift.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_gift.updated_time
     *
     * @return the value of meet_gift.updated_time
     *
     * @mbggenerated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_gift.updated_time
     *
     * @param updatedTime the value for meet_gift.updated_time
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_gift.updated_by
     *
     * @return the value of meet_gift.updated_by
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_gift.updated_by
     *
     * @param updatedBy the value for meet_gift.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_gift.remark
     *
     * @return the value of meet_gift.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_gift.remark
     *
     * @param remark the value for meet_gift.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_gift.deleted
     *
     * @return the value of meet_gift.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_gift.deleted
     *
     * @param deleted the value for meet_gift.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}