package com.liudehuang.boot.druid.entity;

import java.util.Date;

public class MeetRank {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_rank.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_rank.activity_id
     *
     * @mbggenerated
     */
    private Long activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_rank.merchant_id
     *
     * @mbggenerated
     */
    private Long merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_rank.rank_serial
     *
     * @mbggenerated
     */
    private Integer rankSerial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_rank.threshold_type
     *
     * @mbggenerated
     */
    private Integer thresholdType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_rank.threshold_value
     *
     * @mbggenerated
     */
    private Integer thresholdValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_rank.give_amount
     *
     * @mbggenerated
     */
    private Integer giveAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_rank.give_score
     *
     * @mbggenerated
     */
    private Integer giveScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_rank.coupon_flag
     *
     * @mbggenerated
     */
    private Integer couponFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_rank.gift_flag
     *
     * @mbggenerated
     */
    private Integer giftFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_rank.gift_max_value
     *
     * @mbggenerated
     */
    private Integer giftMaxValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_rank.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_rank.created_by
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_rank.updated_time
     *
     * @mbggenerated
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_rank.updated_by
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_rank.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meet_rank.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_rank.id
     *
     * @return the value of meet_rank.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_rank.id
     *
     * @param id the value for meet_rank.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_rank.activity_id
     *
     * @return the value of meet_rank.activity_id
     *
     * @mbggenerated
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_rank.activity_id
     *
     * @param activityId the value for meet_rank.activity_id
     *
     * @mbggenerated
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_rank.merchant_id
     *
     * @return the value of meet_rank.merchant_id
     *
     * @mbggenerated
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_rank.merchant_id
     *
     * @param merchantId the value for meet_rank.merchant_id
     *
     * @mbggenerated
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_rank.rank_serial
     *
     * @return the value of meet_rank.rank_serial
     *
     * @mbggenerated
     */
    public Integer getRankSerial() {
        return rankSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_rank.rank_serial
     *
     * @param rankSerial the value for meet_rank.rank_serial
     *
     * @mbggenerated
     */
    public void setRankSerial(Integer rankSerial) {
        this.rankSerial = rankSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_rank.threshold_type
     *
     * @return the value of meet_rank.threshold_type
     *
     * @mbggenerated
     */
    public Integer getThresholdType() {
        return thresholdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_rank.threshold_type
     *
     * @param thresholdType the value for meet_rank.threshold_type
     *
     * @mbggenerated
     */
    public void setThresholdType(Integer thresholdType) {
        this.thresholdType = thresholdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_rank.threshold_value
     *
     * @return the value of meet_rank.threshold_value
     *
     * @mbggenerated
     */
    public Integer getThresholdValue() {
        return thresholdValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_rank.threshold_value
     *
     * @param thresholdValue the value for meet_rank.threshold_value
     *
     * @mbggenerated
     */
    public void setThresholdValue(Integer thresholdValue) {
        this.thresholdValue = thresholdValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_rank.give_amount
     *
     * @return the value of meet_rank.give_amount
     *
     * @mbggenerated
     */
    public Integer getGiveAmount() {
        return giveAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_rank.give_amount
     *
     * @param giveAmount the value for meet_rank.give_amount
     *
     * @mbggenerated
     */
    public void setGiveAmount(Integer giveAmount) {
        this.giveAmount = giveAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_rank.give_score
     *
     * @return the value of meet_rank.give_score
     *
     * @mbggenerated
     */
    public Integer getGiveScore() {
        return giveScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_rank.give_score
     *
     * @param giveScore the value for meet_rank.give_score
     *
     * @mbggenerated
     */
    public void setGiveScore(Integer giveScore) {
        this.giveScore = giveScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_rank.coupon_flag
     *
     * @return the value of meet_rank.coupon_flag
     *
     * @mbggenerated
     */
    public Integer getCouponFlag() {
        return couponFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_rank.coupon_flag
     *
     * @param couponFlag the value for meet_rank.coupon_flag
     *
     * @mbggenerated
     */
    public void setCouponFlag(Integer couponFlag) {
        this.couponFlag = couponFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_rank.gift_flag
     *
     * @return the value of meet_rank.gift_flag
     *
     * @mbggenerated
     */
    public Integer getGiftFlag() {
        return giftFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_rank.gift_flag
     *
     * @param giftFlag the value for meet_rank.gift_flag
     *
     * @mbggenerated
     */
    public void setGiftFlag(Integer giftFlag) {
        this.giftFlag = giftFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_rank.gift_max_value
     *
     * @return the value of meet_rank.gift_max_value
     *
     * @mbggenerated
     */
    public Integer getGiftMaxValue() {
        return giftMaxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_rank.gift_max_value
     *
     * @param giftMaxValue the value for meet_rank.gift_max_value
     *
     * @mbggenerated
     */
    public void setGiftMaxValue(Integer giftMaxValue) {
        this.giftMaxValue = giftMaxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_rank.created_time
     *
     * @return the value of meet_rank.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_rank.created_time
     *
     * @param createdTime the value for meet_rank.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_rank.created_by
     *
     * @return the value of meet_rank.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_rank.created_by
     *
     * @param createdBy the value for meet_rank.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_rank.updated_time
     *
     * @return the value of meet_rank.updated_time
     *
     * @mbggenerated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_rank.updated_time
     *
     * @param updatedTime the value for meet_rank.updated_time
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_rank.updated_by
     *
     * @return the value of meet_rank.updated_by
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_rank.updated_by
     *
     * @param updatedBy the value for meet_rank.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_rank.remark
     *
     * @return the value of meet_rank.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_rank.remark
     *
     * @param remark the value for meet_rank.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meet_rank.deleted
     *
     * @return the value of meet_rank.deleted
     *
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meet_rank.deleted
     *
     * @param deleted the value for meet_rank.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
}