server:
  port: 8092
spring:
  application:
    name: sentinel-core-learn
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #配置Nacos地址
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080 #配置sentinel dashboard地址
        port: 8719
      #filter:
        #enabled: false