server:
  port: 8098
spring:
  application:
    name: sentinel-cluster-embedded
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719

