package com.liudehuang.boot.druid.mapper;

import com.liudehuang.boot.druid.entity.KanjiaRecord;

public interface KanjiaRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kanjia_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kanjia_record
     *
     * @mbggenerated
     */
    int insert(KanjiaRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kanjia_record
     *
     * @mbggenerated
     */
    int insertSelective(KanjiaRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kanjia_record
     *
     * @mbggenerated
     */
    KanjiaRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kanjia_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(KanjiaRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kanjia_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(KanjiaRecord record);
}