package com.liudehuang.boot.druid.mapper;

import com.liudehuang.boot.druid.entity.MeetRank;

public interface MeetRankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meet_rank
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meet_rank
     *
     * @mbggenerated
     */
    int insert(MeetRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meet_rank
     *
     * @mbggenerated
     */
    int insertSelective(MeetRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meet_rank
     *
     * @mbggenerated
     */
    MeetRank selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meet_rank
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MeetRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meet_rank
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MeetRank record);
}