package com.liudehuang.boot.druid.mapper;

import com.liudehuang.boot.druid.entity.MeetGift;

public interface MeetGiftMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meet_gift
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meet_gift
     *
     * @mbggenerated
     */
    int insert(MeetGift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meet_gift
     *
     * @mbggenerated
     */
    int insertSelective(MeetGift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meet_gift
     *
     * @mbggenerated
     */
    MeetGift selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meet_gift
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MeetGift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meet_gift
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MeetGift record);
}