server:
  port: 8071

spring :
  datasource :
    url : jdbc:mysql://localhost:3306/user_rbac?useUnicode=true&amp;characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true&useSSL=false
    username : root
    password : 123456
    driverClassName : com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    password:
    database: 2
    port: 6379
mybatis:
  mapper-locations: classpath:mapper/*.xml

# JWT
jwt:
  header: Authorization
  secret: mySecret
  #token有效期一天
  expiration: 86400
  tokenHead: "Bearer "
logging:
  level:
    com.liudehuang: debug
    org.springframework.data: debug
    org.apache.ibatis: debug
